/* ============================================================================
   BTR PROJECT CATALOG
   ============================================================================
   This file holds every project shown on projects.html.
   To add a new project, copy one of the existing entries below, paste it
   just before the closing  ];  and edit the fields.

   FULL INSTRUCTIONS: see README.md in the repo root.

   FIELDS: title, supervisor, institution, location, email, disciplines[],
           types[], description, dateAdded (required) +
           background, details[], methods, recommended, note (optional)

   ALLOWED DISCIPLINES: Bioinformatics, Biomedical Sciences, Biotechnology,
     Chemistry, Ecology & Fieldwork, Materials Science, Neuroscience,
     Physics, Sustainability, Other
   ALLOWED TYPES: Lab, Data Analysis, Simulation, Modelling
   ============================================================================ */

window.BTR_PROJECTS = [
  {
    title: "X-ray Diffraction for Sustainable Materials Characterization",
    supervisor: "Dr. Marina Borzova",
    institution: "Eindhoven University of Technology",
    location: "Eindhoven",
    email: "m.borzova@tue.nl",
    disciplines: ["Materials Science","Sustainability","Chemistry"],
    types: ["Lab","Data Analysis"],
    description: "Improve XRD analysis methods for Electric Arc Furnace (EAF) slags as supplementary cementitious materials in the steel industry's sustainability transition.",
    background: "The steel industry accounts for 4–5% of global CO2 emissions, with over 400 million tonnes of slag produced annually. EAF slags are increasingly replacing traditional Blast Oxygen Furnace (BOF) slags as the industry becomes more sustainable. XRD is crucial for identifying and quantifying crystalline phases, but its reliability decreases when analysing samples with amorphous phases or unknown compositions — particularly relevant for heterogeneous EAF slags whose composition varies with production conditions.",
    objectives: ["Improve accuracy and reliability of XRD analysis for EAF slag characterization","Identify potential sources of inaccuracies in XRD measurements","Develop solutions to minimise measurement errors","Assess potential applications of EAF slags as supplementary cementitious materials"],
    details: ["XRD data collection from various slag samples provided by project partners","Optimisation of measurement conditions and instrumental settings","Use of internal and external standards","Validation through complementary techniques: SEM-EDX, XRF","Exploration of different data analysis approaches using open-source software and modelling"],
    methods: "XRD, SEM-EDX, XRF, open-source data analysis and modelling",
    recommended: "No prior hands-on experience with analytical techniques required — full training provided in experimental methods, data analysis and scientific concepts.",
    note: "Part of a large collaboration with steel producers, research institutes and PhD students. Project aims can be adapted to student interests; scope is defined during the first month with student input. Potential for joint publication if the project progresses successfully.",
    references: ["Skaf, M. et al. (2017). EAF slag in asphalt mixes: a brief review. Resources, Conservation and Recycling, 120, 176–185.","Snellings, R. et al. (2014). The existence of amorphous phase in Portland cements. Cement and Concrete Research, 59, 139–146.","Snellings, R. et al. (2014). Use of X-ray diffraction to quantify amorphous SCMs. Cement and Concrete Research, 64, 89–98."],
    dateAdded: "2026-01"
  },
  {
    title: "Modeling Hemodialysis & the Bioartificial Kidney",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Advance computational models of hemodialysis to design new treatments such as the bioartificial kidney and reduce water usage during dialysis.",
    background: "The Carlier group uses computational biology and mathematical models (ODEs, PDEs, agent-based models in VCell, Python, Matlab) to explore design principles of biological systems and optimise treatments. Current applications focus on kidney physiology and pathology, kidney treatment devices, and cell–biomaterial interactions.",
    objectives: ["Design new treatments such as the bioartificial kidney","Reduce water usage during dialysis","Advance in silico models that capture the physiology of treatment devices"],
    methods: "ODEs, PDEs, agent-based models (VCell, Python, Matlab)",
    note: "Collaboration with UMC Utrecht.",
    dateAdded: "2025-11"
  },
  {
    title: "Kidney Physiology: Proximal Tubule & PBPK Modeling",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Modelling"],
    description: "Develop in silico models of nephrons capturing toxin transport, drug interactions and metabolism in healthy, CKD and AKI states.",
    background: "Several sub-projects are available, each tackling a different aspect of kidney physiology and pharmacokinetics. Students can pick a focus based on their interests.",
    details: ["A. Proximal tubule mitochondria metabolism model/map — in silico models of nephron segments capturing toxin transport, drug interactions and metabolism in health and disease","B. PBPK model for healthy, CKD and AKI states — physiologically-based pharmacokinetic modelling with applications in chronic and acute kidney injury","C. PBPK model for sex differences — investigating sex-specific differences in kidney physiology and drug response","D. Model linking proximal tubule metabolism and transport — integrating metabolic and transport processes","E. Model/map of PT transport in physiology and CKD — comprehensive mapping of proximal tubule transport mechanisms"],
    methods: "ODEs, PDEs, pathway mapping (VCell, Python, Matlab)",
    dateAdded: "2025-11"
  },
  {
    title: "Disease Map of Fibrosis",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Modelling"],
    description: "Create an extensive visual representation of signaling pathways involved in fibrosis and dynamically model a subset of them.",
    background: "Part of the Carlier group's cell–biomaterial interaction research line. Combines pathway mapping with dynamic computational modelling to understand fibrotic disease mechanisms.",
    details: ["Create an extensive visual representation of signalling pathways involved in fibrosis","Select and dynamically model a subset of pathways","Integrate literature-derived interactions into a coherent map"],
    methods: "Pathway mapping, dynamic ODE modelling (VCell, Python)",
    dateAdded: "2025-11"
  },
  {
    title: "Lung Model for Inhalation Risk Assessment",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Develop a model assessing the effect of inhaled substances on lung disease, supporting public health risk assessment.",
    background: "Part of the Carlier group's cell–biomaterial interaction research line, in collaboration with RIVM. Supports public health risk assessment initiatives for inhaled substances.",
    methods: "ODEs/PDEs, agent-based modelling (VCell, Python, Matlab)",
    note: "Collaboration with RIVM (Dutch National Institute for Public Health and the Environment).",
    dateAdded: "2025-11"
  },
  {
    title: "Bone Regeneration with Co-morbidities",
    supervisor: "Dr. Aurélie Carlier",
    institution: "MERLN Institute, Maastricht University",
    location: "Maastricht",
    email: "a.carlier@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Model how bone regeneration is affected by co-morbidities to improve treatment strategies for patients with multiple conditions.",
    background: "Part of the Carlier group's cell–biomaterial interaction research line. Builds an in silico model of bone regeneration that can be perturbed to study the effect of co-morbidities (e.g. diabetes, osteoporosis) on healing.",
    methods: "ODE and agent-based modelling (VCell, Python, Matlab)",
    dateAdded: "2025-11"
  },
  {
    title: "Host-Microbiome Interactions in Aging Female Mice",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Data Analysis","Modelling"],
    description: "Reconstruct gut bacterial genomes from female mice at 3, 15 and 24 months and integrate with host gene expression to study sex-specific aging.",
    background: "Recent findings published in Nature Microbiology (Best et al. 2025) highlighted numerous host–microbiome interactions differentially regulated across the murine lifespan, with age-dependent metabolic interactions identified along gut–brain and gut–liver axes in male mice. This follow-up project investigates these patterns in female mice to understand sex-specific differences.",
    objectives: ["Reconstruct gut bacterial genomes from metagenomic sequencing data of colon contents (3, 15 and 24 months)","Analyse host gene expression in brain and colon to assess age-related transcriptomic changes","Perform integrative analyses to identify metabolic and regulatory interactions between microbes and host tissues during aging"],
    details: ["Assembly and annotation of metagenomic data to reconstruct microbial genomes and functional capacities","Analysis of host RNA-seq data from colon and brain tissues","Integration using metabolic modelling, partial correlation analysis, random forests or weighted gene co-expression networks (WGCNA)"],
    methods: "Metagenomics assembly, RNA-seq, metabolic modelling, R/Python",
    recommended: "Background in bioinformatics, computational biology or life sciences. Basic familiarity with genomics or transcriptomics. Confidence in handling large datasets (R or Python).",
    note: "Purely computational (dry lab). BSc project focuses on Objective 1 OR 2. Available BSc or MSc thesis level.",
    references: ["Best, L., Dost, T., Esser, D. et al. Metabolic modelling reveals the aging-associated decline of host–microbiome metabolic interactions in mice. Nat Microbiol 10, 973–991 (2025). https://doi.org/10.1038/s41564-025-01959-z"],
    dateAdded: "2025-11"
  },
  {
    title: "Eukaryotic Metabolic Modeling via Stochastic Petri Nets",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Develop an alternative to Flux Balance Analysis for multicellular metabolism using product-inhibition Petri Net models.",
    background: "Metabolic modelling traditionally uses Flux Balance Analysis (FBA), which assumes cellular metabolism is optimised for specific goals like growth. This works well for microorganisms and tumour cells, but is challenging for multicellular organisms where metabolic goals are less clear. This project develops an alternative approach based on product inhibition as the main source of regulation, implemented as a Petri Net where (i) all substrates must be available in needed quantity to produce products and (ii) the sum of substrate concentrations must exceed the sum of product concentrations.",
    objectives: ["Identify the mechanisms of early reaction blocking in these models","Improve modelling predictions by integrating reaction constants and enzyme concentrations","Evaluate how well the approach recapitulates experimental data"],
    methods: "C++, Python, Petri Net simulation",
    recommended: "Essential: good understanding of C++ and Python. Fair understanding of biochemical processes and kinetics (or willingness to learn). Spoken and written English.",
    note: "BSc or MSc thesis level. Purely computational.",
    references: ["Orth, J. D. et al. (2010). What is flux balance analysis? Nat. Biotechnol., 28(3), 245–248.","Koch, I. (2015). Petri nets in systems biology. Softw. Syst. Model., 14(2), 703–710."],
    dateAdded: "2025-11"
  },
  {
    title: "Machine Learning for Medium Predictions in Metabolic Modeling",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Data Analysis","Modelling"],
    description: "Use ML to predict bacterial growth media from genome-derived draft metabolic models, improving culture-free model construction.",
    background: "Metabolic model construction from genomic information is largely automated but depends on knowing growth conditions (medium composition) for efficient gap filling. For culture-free methods like metagenomics these conditions are unknown and must be estimated from draft models. Growth media from the German Collection of Microorganisms and Cell Culture (DSMZ) have been collected and translated together with genomes of bacteria growing on these media — providing a labelled dataset for machine learning.",
    objectives: ["Generate draft metabolic models from bacterial genomes","Associate metabolic functions to compounds in growth media","Train and evaluate ML models to predict suitable media"],
    methods: "R, gapseq, machine learning, SLURM/HPC",
    recommended: "Programming experience in R, preferably in a high-performance computing environment (SLURM). Fair understanding of machine learning algorithms and applications. Spoken and written English.",
    note: "Purely computational. BSc thesis level.",
    references: ["Zimmermann, J. et al. (2021). gapseq: informed prediction of bacterial metabolic pathways. Genome Biol., 22(1), 81.","Koblitz, J. et al. (2023). MediaDive: the expert-curated cultivation media database. Nucleic Acids Res., 51(D1), D1531–D1538."],
    dateAdded: "2025-11"
  },
  {
    title: "Steroid Hormones & the Gut Microbiome",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Biomedical Sciences","Bioinformatics"],
    types: ["Data Analysis","Modelling"],
    description: "Investigate whether menopause-related hormonal changes (and HRT) impact gut microbiome composition using a northern German cohort.",
    background: "Recent research shows that as we age, the interaction between gut microbiome and host weakens and cooperation among microbial species decreases. This project investigates whether age-related hormonal changes — particularly those associated with menopause — contribute to alterations in the gut microbiome.",
    objectives: ["Analyse gut microbiome composition and biomarkers in pre- and post-menopausal women from a northern German cohort","Investigate the effects of Hormone Replacement Therapy (HRT) on microbiome structure, diet and blood metabolome","Examine whether changes in bacterial metabolism are reflected in blood biomarkers"],
    methods: "Classic statistical methods, data visualization, metabolic modelling (R/Python)",
    recommended: "Background in life sciences, informatics or data analysis beneficial.",
    note: "Purely computational. BSc focuses on objective 1 or 2. BSc or MSc thesis level. Provides hands-on experience with real-world human cohort data.",
    references: ["Best, L. et al. (2025). Metabolic modelling reveals the aging-associated decline of host–microbiome metabolic interactions in mice. Nature Microbiology, https://doi.org/10.1038/s41564-025-01959-z"],
    dateAdded: "2025-11"
  },
  {
    title: "Metabolite Exchange Networks of the Aging Gut Microbiome",
    supervisor: "Lena Best & Prof. Christoph Kaleta",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "L.Best@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Data Analysis","Modelling"],
    description: "Use drop-out community simulations to characterise how 'egoistic' bacteria affect microbial metabolite exchange and stability with age.",
    background: "Research shows that as individuals age, interaction between gut microbiome and host weakens and cooperation among bacteria decreases. Drop-out community simulations (removing certain 'egoistic' bacteria) show increased growth, improved productivity and better nutrient use. These 'egoistic' bacteria become more dominant in old mice, coinciding with increased competition for nutrients.",
    objectives: ["Characterise how 'egoistic' bacteria affect microbial metabolite exchange","Assess efficiency of nutrient utilisation","Evaluate microbiome community stability","Long-term: identify targets for microbiome-based interventions against age-related decline"],
    details: ["Integrate age with metabolite exchange data into correlation networks","Network topology analysis of community stability and metabolite utilisation","MSc extension: simulate alternative diets with metabolites added/removed to reduce detrimental 'egoistic' bacteria"],
    methods: "Network analysis, community simulation, R",
    note: "Purely computational. BSc or MSc thesis level.",
    references: ["Best, L. et al. (2025). Metabolic modelling reveals the aging-associated decline of host–microbiome metabolic interactions in mice. Nature Microbiology, https://doi.org/10.1038/s41564-025-01959-z"],
    dateAdded: "2025-11"
  },
  {
    title: "Bacterial Niche Formation in Nematostella vectensis Microbiome",
    supervisor: "Dr. Jan Taubenheim & Dr. Johannes Zimmermann",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics","Ecology & Fieldwork"],
    types: ["Simulation","Modelling"],
    description: "Test whether early microbial colonisers of the sea anemone Nematostella create niches for later bacteria via metabolic interactions.",
    background: "Nematostella vectensis is a sea anemone with high adaptability to different environmental conditions. It belongs to Cnidaria, sister group to all Bilateria, providing insights into evolution, development and symbiosis. Nematostella harbours a specific microbial community that changes over developmental stages. Strikingly, these microbiome changes are recapitulated when germfree adult polyps are recolonised with their own microbiota, suggesting early microbial colonisers create environmental niches for subsequent bacteria.",
    objectives: ["Investigate pairwise metabolic interactions between ~60 'early' and 'late' coloniser bacteria","Reconstruct metabolic models with gapseq","Simulate bacteria pairs with bacarena","Predict growth and exchanged metabolites and provide data for wet-lab validation"],
    methods: "gapseq, bacarena (agent-based metabolic modelling), R, Python, Unix",
    recommended: "Basic knowledge of R computing (mandatory). Basic knowledge of Python and Unix environments is advantageous.",
    note: "Master thesis level. Wet-lab partner confirms predictions — direct contact with experimental partners for networking.",
    references: ["Mortzfeld, B. M. et al. (2016). Bacterial colonization in Nematostella vectensis. Environ. Microbiol., 18(6), 1764–1781.","Zimmermann, J. et al. (2021). gapseq. Genome Biol., 22(1), 81.","Bauer, E. et al. (2017). BacArena: individual-based metabolic modeling. PLOS Comput. Biol., 13(5), e1005544."],
    dateAdded: "2025-11"
  },
  {
    title: "Curvibacter in Hydra Microbiome Assembly",
    supervisor: "Dr. Jan Taubenheim",
    institution: "Christian-Albrechts-University Kiel — Institute of Experimental Medicine",
    location: "Kiel, Germany",
    email: "j.taubenheim@iem.uni-kiel.de",
    disciplines: ["Bioinformatics"],
    types: ["Data Analysis","Modelling"],
    description: "Use RNA-seq across conditions to study how Curvibacter — the dominant bacterium of the freshwater polyp Hydra — adapts its metabolism.",
    background: "The freshwater polyp Hydra harbours a simple microbiome dominated (~80%) by Curvibacter, a bacterium essential for Hydra's metabolism, development and immunity. Although Curvibacter is self-sufficient and can live freely, its dominance suggests active recruitment by the host. RNA-seq data are available for Curvibacter grown under (i) monoculture on different media, (ii) mono-colonisation of Hydra and (iii) as part of Hydra's native microbiome.",
    objectives: ["Determine how gene expression of Curvibacter changes across conditions","Determine how metabolic potential of Curvibacter changes across conditions","Assess how changed metabolism translates into microbiome–microbiome interactions"],
    details: ["Differential gene expression analyses and gene set enrichment analysis","Reconstruction and analysis of context-specific metabolic models","Modelling metabolic interactions with other key members of the Hydra microbiome"],
    methods: "RNA-seq analysis, context-specific metabolic modelling, R/Python",
    recommended: "Background in bioinformatics, computational biology or life sciences beneficial. Basic familiarity with genomics or transcriptomics. Confidence in handling datasets (R or Python). Open for your own ideas.",
    note: "BSc or MSc thesis level. Project focus can be adjusted to student's background and interests.",
    references: ["Minten-Lange, T. & Fraune, S. (2020). Hydra and Curvibacter. In Cellular Dialogues in the Holobiont, 79–89.","Fraune, S. et al. (2015). Bacteria–bacteria interactions within the microbiota of Hydra. ISME J, 9(7), 1543–1556.","Pietschke, C. et al. (2017). Host modification of a bacterial quorum-sensing signal. PNAS, 114(40)."],
    dateAdded: "2025-11"
  },
  {
    title: "Interactive Biological Pathways for Rare Diseases",
    supervisor: "Dr. Friederike Ehrhart",
    institution: "Maastricht University — Department of Translational Genomics",
    location: "Maastricht (Universiteitssingel 60, M1.06)",
    email: "friederike.ehrhart@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics","Biomedical Sciences"],
    types: ["Data Analysis","Modelling"],
    description: "Curate, model and publish molecular pathway diagrams of rare diseases on WikiPathways and analyse omics data with them.",
    background: "Pathway diagrams are powerful tools to communicate molecular processes and, when properly annotated, become immensely useful for computational analysis of large datasets. WikiPathways (www.wikipathways.org) allows researchers to share and discuss pathway models. Rare diseases occur in less than 1:2,000 in a population — examples include ALS, Phenylketonuria (PKU) and Huntington's disease — but the biological pathways of many rare diseases are not known, not yet published, or hidden in other contexts in databases or publications.",
    objectives: ["Analyse literature and databases to identify responsible genes for a rare disease and map their interactions","Cluster genes into molecular pathways, draw them in PathVisio with full annotation and publish on WikiPathways","Analyse expression data by visualising it on the pathway and exploring rare-disease networks in Cytoscape (e.g. drug targets, regulatory extensions)"],
    details: ["Pathway modelling","Network analysis","Omics data analysis","Data integration"],
    methods: "PathVisio, WikiPathways, Cytoscape, omics analysis",
    recommended: "Computer skills — must be able to install PathVisio independently. Laptop with >100 MB free disk space.",
    note: "CRITICAL: PathVisio must run smoothly on your laptop — test installation before committing to the project.",
    dateAdded: "2025-11"
  },
  {
    title: "Herbarium of the Jochymhof — Limburg Flora",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Lab","Data Analysis"],
    description: "Investigate ~1,000 herbarium specimens of the Jochymhof botanical garden in Steyl and write a small data paper.",
    background: "The Erkens group investigates evolutionary plant biology — how and when plant diversity originated — across two main study areas: (South) Limburg and the Neotropics. This project opens up the uninvestigated herbarium collections of the Jochymhof botanical garden in Steyl.",
    details: ["Study circa 1,000 herbarium specimens","Document specimens","Analyse how the collection adds to current knowledge of the flora of Limburg","Write a small data paper based on the analyses"],
    note: "Aim: publication of a data paper.",
    dateAdded: "2025-11"
  },
  {
    title: "Redlisting of Trees and Lianas in Annonaceae",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Data Analysis"],
    description: "Make IUCN Red List threat assessments for species in the pantropical plant family Annonaceae.",
    background: "The supervisor is a member of the Global Tree Assessment group that prepares official reports for the IUCN Red List. Student assessments of Annonaceae trees and lianas feed directly into these official reports.",
    details: ["Compile distribution and threat data for selected Annonaceae species","Apply IUCN criteria to assign threat categories","Produce assessments suitable for publication in yearly IUCN Red List updates"],
    note: "Assessments are published as part of the yearly IUCN Red List updates (https://www.iucnredlist.org/).",
    dateAdded: "2025-11"
  },
  {
    title: "Biogeographical Patterns in Annonaceae using GIS",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Bioinformatics"],
    types: ["Data Analysis"],
    description: "Use GIS to investigate what determines the distribution of species in the plant family Annonaceae.",
    background: "Annonaceae is a pantropical plant family with striking biogeographical patterns. This project asks what geographical, environmental and historical factors determine present-day species distributions.",
    methods: "Geographical Information Systems (GIS) analyses, spatial statistics",
    note: "Collaboration with the University of Montpellier, France.",
    dateAdded: "2025-11"
  },
  {
    title: "Morphological Traits of Guatteria Species",
    supervisor: "Dr. Roy Erkens",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork"],
    types: ["Lab","Data Analysis"],
    description: "Investigate the poorly understood Neotropical genus Guatteria using SEM pollen work or leaf morphometric analyses.",
    background: "Guatteria is the supervisor's 'pet genus' and is poorly understood — it is open for investigation on many fronts, from pollen morphology to leaf anatomy.",
    details: ["Pollen work using Scanning Electron Microscopy (SEM)","Leaf analyses using morphometric techniques"],
    methods: "SEM, morphometrics",
    dateAdded: "2025-11"
  },
  {
    title: "Chemical Constituents and Crystals of Tropical Plants",
    supervisor: "Dr. Roy Erkens (with Giuditta Perversi)",
    institution: "Maastricht University — System Earth Science",
    location: "Brightlands Campus Greenport Venlo",
    email: "roy.erkens@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Chemistry"],
    types: ["Lab"],
    description: "Study the secondary compounds and crystals found in leaves of tropical plant species.",
    background: "Tropical plants are well known for the large number of secondary compounds and crystals they produce in their leaves. Many of these need study and review. Project run in collaboration with Giuditta Perversi.",
    dateAdded: "2025-11"
  },
  {
    title: "Network Analysis of Interictal Abnormalities in Stereo-EEG",
    supervisor: "Dr.ir. E.D. Gommer",
    institution: "MUMC+ — Department of Clinical Neurophysiology",
    location: "Maastricht",
    email: "e.gommer@mumc.nl",
    disciplines: ["Neuroscience","Bioinformatics","Biomedical Sciences"],
    types: ["Data Analysis","Modelling"],
    description: "Implement and evaluate network-based methods to localise the epileptogenic zone using interictal SEEG recordings of drug-resistant epilepsy patients.",
    background: "Patients with drug-resistant epilepsy may undergo radiofrequency thermocoagulation or surgical resection. A critical step is accurate identification of the epileptogenic zone through multimodal imaging and intracranial EEG. Stereo-EEG (SEEG) provides high-resolution depth recordings allowing detailed analysis of epileptic activity and network interactions. Recent studies suggest epileptogenic regions are not isolated but embedded in pathological networks with distinctive connectivity patterns that may predict surgical outcome.",
    objectives: ["Phase 1 — Identify candidate pathological nodes from interictal SEEG: regions with increased interictal spike rates and abnormal time-frequency characteristics","Phase 2 — Perform connectivity and network analyses on the identified abnormal regions","Characterise how these regions interact with the rest of the brain network","Contribute to improved presurgical evaluation"],
    methods: "Interictal SEEG analysis, spike detection, time-frequency analysis, connectivity and graph-theoretic network analysis",
    dateAdded: "2026-01"
  },
  {
    title: "Cellular Plant Development Modelling with VirtualLeaf",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Simulation","Modelling"],
    description: "Use the VirtualLeaf framework to simulate plant tissue growth and developmental processes (e.g. root growth) at cellular level.",
    background: "VirtualLeaf is a computational framework for simulating plant tissue growth and development at the cellular level. The Großeholz group combines mathematical modelling with biological insight to address questions from cellular signalling to organ-level development.",
    details: ["Model specific developmental processes such as root growth","Analyse source–sink relationships between tissues","Combine biological knowledge with computational implementation","Explore how simple cellular rules give rise to complex tissue-level patterns"],
    methods: "VirtualLeaf, computational modelling",
    recommended: "Interest in both computational methods and plant biology. Basic programming experience (language flexible). Comfort with quantitative reasoning. No prior modelling experience required — enthusiasm to learn is most important.",
    dateAdded: "2025-11"
  },
  {
    title: "Environmental Responses in Plant Models",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Expand existing plant modelling frameworks to incorporate environmental factors such as temperature and light quality.",
    background: "Projects bridge computational modelling with plant physiology and ecology, addressing how plants adapt to their environment.",
    details: ["Temperature effects on growth and development","Light quality responses","General environmental integration into existing models"],
    recommended: "Existing programming skills required. Interest in plant physiology and ecology.",
    dateAdded: "2025-11"
  },
  {
    title: "Multi-Scale Plant Signaling and Response Models",
    supervisor: "Dr. Ruth Großeholz",
    institution: "Maastricht University",
    location: "Maastricht",
    email: "ruth.grosseholz@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Modelling","Simulation"],
    description: "Build models linking molecular signalling and cellular responses, from ODE-based signalling to particle-based protein movement.",
    background: "Develop models that connect different biological scales — from molecular signalling to cellular responses — in plant systems.",
    details: ["ODE-based signalling models","Particle-based models for protein movements","Linking molecular and cellular scales"],
    methods: "ODE modelling, particle-based simulation",
    recommended: "Basic programming experience; interest in plant biology and quantitative reasoning.",
    dateAdded: "2025-11"
  },
  {
    title: "Ancient Technology and Innovation",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Lab","Data Analysis"],
    description: "Explore the technological, environmental and cultural factors influencing ancient inventions in the eastern Mediterranean.",
    background: "Dr. Jazwa's research focuses on ancient technology, construction, science and settlement — especially in the eastern Mediterranean (Greece, Cyprus). Several datasets are available that can form the foundation for various BTR projects.",
    recommended: "Especially encouraged: students with experience in ArcGIS, Microsoft Access database design, photogrammetry, programming, statistics or digital reconstructions.",
    dateAdded: "2025-11"
  },
  {
    title: "Mapping Ancient Landscapes",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Data Analysis"],
    description: "Map natural resources, transportation routes, biological and geological data to study past human settlement patterns.",
    background: "Part of the Jazwa research programme on ancient landscapes. Maps natural resources, transportation routes, and biological and geological data to explore relationships with past human settlements and their influence on artifact distributions.",
    details: ["Map natural resources and transportation routes","Integrate biological and geological datasets","Explore links with past human settlement and artifact distribution"],
    methods: "ArcGIS, statistics, photogrammetry, database analysis",
    recommended: "ArcGIS, database design, statistics or photogrammetry experience strongly encouraged.",
    dateAdded: "2025-11"
  },
  {
    title: "Human Behavioral Ecology of Past Settlement",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Data Analysis","Modelling"],
    description: "Apply ecological models to past human settlement data to understand how landscapes were inhabited and used.",
    background: "Human Behavioral Ecology applies ecological models to past human settlement data to understand how landscapes became inhabited and used over time.",
    recommended: "Experience in statistics, programming or GIS encouraged.",
    dateAdded: "2025-11"
  },
  {
    title: "Experimental Archaeology",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Other"],
    types: ["Lab"],
    description: "Recreate ancient technologies and structures (e.g. Bronze Age building) to test hypotheses about how things were made and used.",
    background: "Experimental archaeology recreates ancient technologies and structures to test hypotheses about how things were made, consumed and used in the past.",
    details: ["How ancient artifacts and structures were made","How they were consumed/used","What their production tells us about the people who made them"],
    dateAdded: "2025-11"
  },
  {
    title: "Ancient Beer: Reconstructing Brewing Recipes",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Chemistry","Other"],
    types: ["Lab","Data Analysis"],
    description: "Reconstruct ancient brewing methods using archaeological, scientific and literary evidence, and document modern recreations.",
    background: "Reconstructing ancient brewing methods and recipes draws on a combination of archaeological, scientific and literary evidence. The project also documents the modern phenomenon of ancient beer recreations.",
    details: ["Archaeological evidence","Scientific evidence","Literary evidence","Modern recreations of ancient beers"],
    dateAdded: "2025-11"
  },
  {
    title: "Prehistoric Water Management Systems",
    supervisor: "Dr. Kyle Jazwa",
    institution: "Maastricht Science Programme",
    location: "Maastricht (PHS1 B2.015)",
    email: "k.jazwa@maastrichtuniversity.nl",
    disciplines: ["Ecology & Fieldwork","Sustainability","Other"],
    types: ["Data Analysis"],
    description: "Examine how prehistoric people manipulated landscapes and built structures to manage rivers and water supplies.",
    background: "Prehistoric water management systems reveal how early societies manipulated landscapes and built structures to manage rivers and water supplies — with lessons for sustainability today.",
    dateAdded: "2025-11"
  },
  {
    title: "Tomato Knowledge Graph from Literature Curation",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Data Analysis"],
    description: "Build a curated knowledge graph linking tomato genes, traits, metabolites, pathways, QTLs and disease-resistance using Text2Trait and HARVEST.",
    background: "Tomato (Solanum lycopersicum) is one of the most studied crops with thousands of papers describing genes, QTLs, metabolites, phenotypes, disease resistance, fruit quality and developmental processes. However, this knowledge is scattered across scientific literature and rarely integrated into a single structured resource. The goal is to create a curated, high-quality Knowledge Graph using the Text2Trait (www.text2trait.com) and HARVEST (www.text2trait.com/harvest) platforms.",
    objectives: ["Which tomato genes are repeatedly associated with a trait across different studies?","Are there metabolites or pathways consistently linked to a trait?","Can we identify 'hub genes' that appear across multiple independent papers?","How well do published QTL candidate genes match known pathway knowledge?","Are there unexplored or weakly studied genes that appear important across different studies?"],
    details: ["Curate Gene→Pathway, Gene→Metabolite, Gene→Trait, Metabolite→Trait relationships","Capture gene/metabolite→stress response and gene→disease resistance (e.g. Botrytis)","Link QTL regions to candidate genes","Build information-extraction use cases: metabolic pathways, tomato–pathogen, tomato–insect and tomato–beneficial microbe interactions"],
    methods: "Text2Trait, HARVEST, literature curation, knowledge graphs",
    note: "You contribute real curated data and may uncover new connections hidden across different papers. Data will be published.",
    dateAdded: "2025-12"
  },
  {
    title: "Normalization Effects on Transcriptomics-Metabolomics Integration",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Data Analysis"],
    description: "Investigate how different normalization strategies (log, Z-score, quantile, CPM/RPKM) affect gene-metabolite correlations in paired multi-omics data.",
    background: "Normalization is essential before integrating multi-omics datasets. Different methods (log scaling, Z-score, quantile normalization, CPM/RPKM) produce different structures in the data and influence correlation strength between omics layers — but there is no consensus on which method is most appropriate for paired transcriptomics–metabolomics data.",
    objectives: ["How do different normalization strategies change data distribution?","How does normalization affect gene–metabolite correlations?","Do some normalization methods artificially inflate or suppress relationships?","Which method is most appropriate for paired transcriptomics–metabolomics data?"],
    methods: "Multi-omics analysis, statistics, R/Python",
    dateAdded: "2025-12"
  },
  {
    title: "Genomic Boundaries of Plant Biosynthetic Gene Clusters",
    supervisor: "Dr. Kumar Saurabh Singh",
    institution: "Brightlands Future Farming Institute",
    location: "Brightlands Campus Greenport Venlo",
    email: "kumarsaurabh.singh@maastrichtuniversity.nl",
    disciplines: ["Bioinformatics"],
    types: ["Data Analysis"],
    description: "Use linkage disequilibrium patterns to investigate the boundaries of biosynthetic gene clusters (BGCs) producing plant natural products.",
    background: "Plants produce a wide variety of natural products with important pharmacological and industrial applications. These are often synthesized by biosynthetic gene clusters (BGCs) encoded in the plant genome. Identifying the genomic boundaries of BGCs is challenging, but recent research has shown that population genomic approaches — particularly linkage disequilibrium (LD) analysis — can provide valuable insights.",
    objectives: ["Investigate LD patterns between genes within BGCs","Compare to LD patterns of non-BGC genes in the same genome","Examine functional relationships between genes within BGCs","Analyse roles in synthesising specific natural products"],
    methods: "Population genomics, linkage disequilibrium analysis, BGC prediction tools",
    dateAdded: "2025-12"
  },
  {
    title: "Cucumber Transformation Method Development",
    supervisor: "Dr. Xinping Yang",
    institution: "Plant Functional Genomics — Brightlands Greenport Venlo",
    location: "Brightlands Campus Greenport Venlo",
    email: "xinping.yang@maastrichtuniversity.nl",
    disciplines: ["Biotechnology"],
    types: ["Lab"],
    description: "Develop a robust transformation pipeline for two contrasting cucumber varieties, optimising explant, hormone, medium and Agrobacterium conditions.",
    background: "Dr. Yang's group works on crop engineering to improve agronomically important traits, with a focus on developing reliable and high-efficiency regeneration across major crop species including tomato, cucumber, pea, lettuce and spinach. Efficient plant regeneration is a critical prerequisite for applying gene-editing and genetic transformation tools in modern crop breeding. This project aims to establish an efficient and reproducible transformation workflow for cucumber.",
    objectives: ["Optimise explant type, hormone balance, medium composition and Agrobacterium infection conditions","Gain hands-on experience with the cucumber regeneration system (strong lab foundation already in place)","Apply Agrobacterium-mediated transformation protocols to two different cucumber genotypes","Contribute to expanding transformation capacity for cucumbers with contrasting biological backgrounds"],
    details: ["Plant tissue culture and explant preparation","Medium recipe optimisation and phytohormone formulation","Agrobacterium-mediated transformation","Regeneration and selection of transformed plant tissues"],
    methods: "Plant tissue culture, Agrobacterium-mediated transformation, selection protocols",
    note: "Minimum 3 days/week presence in the Brightlands Venlo lab.",
    dateAdded: "2025-11"
  },
  {
    title: "Hormone Reporter Lines for Tomato Regeneration",
    supervisor: "Dr. Xinping Yang",
    institution: "Plant Functional Genomics — Brightlands Greenport Venlo",
    location: "Brightlands Campus Greenport Venlo",
    email: "xinping.yang@maastrichtuniversity.nl",
    disciplines: ["Biotechnology"],
    types: ["Lab"],
    description: "Generate fluorescent reporter lines visualising auxin/cytokinin signalling during callus induction, shoot initiation and organogenesis in tomato.",
    background: "Builds on a well-established tomato regeneration and transformation platform in the Yang group. Aims to uncover spatial and temporal hormone dynamics throughout tomato regeneration — resulting reporter lines will serve as valuable tools for future developmental and gene-editing studies.",
    objectives: ["Develop technical skills for tomato tissue culture","Learn stable genetic transformation","Analyse fluorescent signals using microscopy","Map hormone responses (auxin, cytokinin) during callus induction, shoot initiation and organogenesis"],
    details: ["Tomato tissue culture and regeneration","Agrobacterium-mediated transformation to introduce reporter constructs","Fluorescence microscopy and image-based analysis of hormone signalling patterns"],
    methods: "Tissue culture, Agrobacterium transformation, fluorescence microscopy",
    note: "Minimum 3 days/week presence in the Brightlands Venlo lab.",
    dateAdded: "2025-11"
  },
  {
    title: "Cytochrome bo3 Oxidase: Substrate/Product Exchange",
    supervisor: "Dr. Ye Gao",
    institution: "M4I Institute — Biochemistry Group",
    location: "Maastricht",
    email: "y.gao@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Biotechnology","Chemistry"],
    types: ["Lab","Data Analysis"],
    description: "Catch intermediate conformations of E. coli cytochrome bo3 quinol oxidase to understand how the enzyme switches between 'open' and 'closed' states during substrate/product exchange.",
    background: "Cytochrome oxidase (complex IV / terminal oxidase) belongs to the heme-copper oxidoreductase superfamily and is part of the respiratory transport chain. It uses electrons from donor substrates to reduce di-oxygen and transports protons across membranes. Cytochrome bo3 quinol oxidase is expressed in E. coli inner membranes at high oxygen levels. The group recently reported a cryo-EM structure in peptidiscs revealing an 'open' conformation allowing substrate/product exchange, complementing the earlier 'closed' conformation for electron transfer and proton pumping. Intermediate structural models are now needed to understand how the enzyme switches between states within the ~5 ms reaction turnover.",
    objectives: ["Design relevant targets using bioinformatics and molecular modelling","Purify recombinant target proteins from non-pathogenic E. coli","Perform structural analysis using data from MS, cryo-EM and complementary techniques"],
    details: ["Bioinformatics, molecular modelling and construct design","Cloning and recombinant expression in E. coli (ML-I conditions)","Membrane protein purification by automated liquid chromatography: IMAC, Ion Exchange, Gel Filtration","Sample characterisation by electrophoresis (Native, SDS-PAGE)","Sample analysis by mass spectrometry","Sample analysis by electron microscopy (negative staining, cryo-EM)"],
    methods: "Cloning, recombinant expression, IMAC/IEX/Gel Filtration, native & SDS-PAGE, mass spectrometry, cryo-EM (core facilities), SAXS and MX at synchrotrons where relevant",
    note: "Available September 2026 onwards — Spring 2026 is full. The M4I Biochemistry group supports protein research for the whole institute.",
    dateAdded: "2025-11"
  },
  {
    title: "LCA of Post-Consumer Beverage Carton Recycling",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability","Materials Science"],
    types: ["Data Analysis","Modelling"],
    description: "Develop a robust EU-wide methodology for calculating recycling rates of fibre-based composite packaging, in collaboration with EXTR:ACT and HEDRA.",
    background: "EXTR:ACT is a pan-European association founded by the beverage carton industry that coordinates and supports actors in the recycling value chain. HEDRA is the Dutch national association for beverage cartons. Based on the 2022 material flow analysis by Schneider, Ghannadzadeh & van der Meer, both partners are interested in extending the methodology — with more precise dry-weight calculations — to all EU countries.",
    objectives: ["Step 1 — Inventory EU methodologies for calculating recycling rates of packaging waste, including pros and cons","Step 2 — Develop a new, robust calculation methodology applicable across EU countries; align with HEDRA and EXTR:ACT data; apply to Germany, Belgium and Spain; include what-if scenarios","Step 3 — Investigate post-separation of beverage cartons from residual waste: potential in the EU, recycling qualities, and impact on political discussions like food safety"],
    details: ["Easy-read but professional report with clear text, diagrams and figures","Simulation tool (e.g. Excel) usable by non-professionals","Webinar presentation to inform EU industry experts"],
    methods: "Material flow analysis, LCA, Excel simulation tool, literature study combined with lab studies",
    note: "Industry partnership with EXTR:ACT (EU) and HEDRA (NL). Contacts: François Rui (f.rui@extr-act.eu), Raymond De Schrevel (r.deschrevel@extr-act.eu), Inge Eggermont (info@hedra.nl), Yvonne van der Meer (yvonne.vandermeer@maastrichtuniversity.nl). Partners provide workshops, regular live contact and deep access to the recycling value chain.",
    dateAdded: "2025-12"
  },
  {
    title: "Dynamic LCA of Microbial Fermentation Bioproducts",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability","Biotechnology"],
    types: ["Data Analysis","Modelling"],
    description: "Apply the BBM-LCA framework to fermentation projects (PHA bioplastics, single cell protein, biosurfactants) at the University of Manitoba.",
    background: "Microbial fermentation is an ancient technology now re-emerging as a way to deliver renewable and sustainable fuels, chemicals and polymers into the bioeconomy. Many commercial fermentation processes still rely on agriculturally derived carbon (glucose, glycerol, plant oils), which is acceptable for high-value pharmaceuticals but not for higher-volume industrial products. To reach industrial scale, processes must utilise low-value waste streams (lignocellulosic residues, starches, whey, slaughterhouse waste) or autotrophic species using CO2. LCA can guide whether the environmental benefits outweigh the inputs, but LCA of bio-based products is not straightforward due to the time dynamics of biogenic carbon. The BBM-LCA framework developed at AMIBM addresses this.",
    objectives: ["Polyhydroxyalkanoate (PHA) biopolymers as potential bioplastics from C1 carbon sources (methanol, formic acid, CO2)","Single cell protein and associated co-products from C1 carbon sources for food/feed applications","Biosurfactant production (and co-products) from sugars derived from lignocellulosic crop residues for biopesticide applications","Bioconversion of pulse starch from plant-based protein sector to single cell oil, carotenoids, bioplastics, biosurfactants","Ethanol and/or 2,3-butanediol production from CO2"],
    methods: "Dynamic LCA, BBM-LCA, ISO 14040 framework",
    note: "External collaboration with Dr. Warren Blunt, University of Manitoba, Canada (warren.blunt@umanitoba.ca).",
    dateAdded: "2025-12"
  },
  {
    title: "Multi-Disciplinary Sustainability Assessment of Biobased Products",
    supervisor: "Dr. Ali Ghannadzadeh",
    institution: "AMIBM — Aachen-Maastricht Institute for Biobased Materials",
    location: "Brightlands Chemelot Campus",
    email: "ali.ghannadzadeh@maastrichtuniversity.nl",
    disciplines: ["Sustainability"],
    types: ["Data Analysis","Modelling"],
    description: "Combine Dynamic LCA, Net Ecosystem Exchange, microplastics, circularity, regulations and exergy analysis into a single sustainability framework.",
    background: "Sustainability assessment of biobased products is not straightforward due to the time dynamics of biogenic carbon — neglecting these dynamics can lead to the inaccurate conclusion that carbon neutrality equals climate neutrality. Levasseur et al. (2010) developed Dynamic LCA to characterise these dynamics, and AMIBM recently combined it with Net Ecosystem Exchange (NEE) in the BBM-LCA framework. This project aims to go further.",
    objectives: ["Dynamic LCA (focus on life cycle inventory)","Net Ecosystem Exchange (NEE)","Microplastics and ecotoxicity","Circularity assessment","Regulations on sustainability","Exergy analysis"],
    methods: "Dynamic LCA, NEE, BBM-LCA, exergy analysis, circularity metrics",
    note: "Additional collaborators: Prof. Dominic Coppens (UM), Prof. Annie Levasseur, Dr. Michael Saidani and Prof. Andrew Henderson (ÉTS Montréal).",
    references: ["https://doi.org/10.1021/es9030003","https://doi.org/10.1002/bbb.2769"],
    dateAdded: "2025-12"
  },
  {
    title: "Non-Crystallizing Deep Eutectic Solvents",
    supervisor: "Dr. Laura Kollau",
    institution: "Circular Chemical Engineering, UM",
    location: "Brightlands Chemelot Campus",
    email: "l.kollau@maastrichtuniversity.nl",
    disciplines: ["Chemistry","Sustainability"],
    types: ["Lab"],
    description: "Investigate fundamental properties of non-crystallizing deep eutectic solvents (DESs) as sustainable alternatives.",
    methods: "DSC, 1D and 2D NMR, organic synthesis",
    dateAdded: "2025-11"
  },
  {
    title: "Structure-Based Virtual Screening for Sepsis",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Chemistry"],
    types: ["Data Analysis","Lab"],
    description: "Use structural bioinformatics and virtual screening to identify drug candidates for severe sepsis.",
    methods: "Structural bioinformatics, molecular docking, virtual screening",
    note: "Limited capacity — interview required.",
    dateAdded: "2025-11"
  },
  {
    title: "Cytotoxic Inflammatory Processes in Sepsis (Histones)",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences","Chemistry"],
    types: ["Lab"],
    description: "Study cytotoxicity of extracellular histones and develop prototype drugs to interfere with histone toxicity in sepsis.",
    methods: "Recombinant protein expression, proteomics, MS, cell culture",
    dateAdded: "2025-11"
  },
  {
    title: "Novel Diagnostic Methods for Sepsis at ICU",
    supervisor: "Dr. Gerry A.F. Nicolaes",
    institution: "Cardiovascular Research Institute Maastricht",
    location: "Maastricht",
    email: "g.nicolaes@maastrichtuniversity.nl",
    disciplines: ["Biomedical Sciences"],
    types: ["Lab"],
    description: "Develop sensitive and fast methods to assess clinical status of ICU sepsis patients using novel biomarkers.",
    methods: "Protein isolation, bioassays, statistical analysis",
    dateAdded: "2025-11"
  },
];
